services:
  minio:
    image: minio/minio:latest
    container_name: construction_minio
    restart: unless-stopped
    ports:
      - "9000:9000"   # MinIO S3 API Endpoint
      - "9001:9001"   # MinIO Web Console UI (Truy cập trình duyệt http://localhost:9001)
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"
